# fly.toml file generated for chemx on 2023-03-18T00:34:24+07:00

app = "chemx"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  REACT_APP_BE_HOST = "https://chemx-staging.fly.dev"
  REACT_APP_BUCKET_URL = "gs://thesis-7edb1.appspot.com"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_51MremvKZ5Ry91xh96OS7EppigE1rRKqGIlSDyVXfhAk6MrPs5Hd01T7GYnxaEBXzu9CAQ88LESuxemCmvRnOoUqR004zo4aoeh"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
