# fly.toml file generated for chemx-staging on 2023-04-01T11:11:29+07:00

app = "chemx-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CLIENT_URL = "https://chemx.fly.dev"
  JWT_SECRET = "vuminhduc"
  MONGODB_URI = "mongodb+srv://minhduc152001:sun291514001@graduation-thesis.eatykkx.mongodb.net/thesis?retryWrites=true&w=majority"
  MONTHLY_PRICE_ID = "price_1MrexDKZ5Ry91xh9kQAwQzOH"
  ANNUALLY_PRICE_ID = "price_1MsHC4KZ5Ry91xh9PUYbGYOX"
  UNLIMITED_PRICE_ID = "price_1MsA2YKZ5Ry91xh9kmWKoVqn"
  PORT = 8081
  STRIPE_API_KEY = "sk_test_51MremvKZ5Ry91xh9AhmBvc5huQiscmsudC7wr9nslRfSdrgVaJV2yJVkCIuZUjVZJrRWpzw53P96KWv9SFX12X6o00TtN6MEij"
  STRIPE_WEBHOOK_SECRET = "whsec_yR1PkA6ZOiDIyU8sjRtbzcdgQpfGmrsK"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
