# fly.toml file generated for chemx-admin on 2023-04-02T22:34:41+07:00

app = "chemx-admin"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 5000
  REACT_APP_BE_HOST = "https://chemx-staging.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
